#!/bin/bash

real_user=$(logname)
real_home=$(eval echo ~$real_user)
api_folder="$real_home/apis/nginx-facts"

# update apt, upgrade system and install nginx, nodejs and npm
echo -e "\e[34mUpdating apt & system and installing nginx, npm and nodejs ...\e[0m"
sudo apt update && sudo apt upgrade -y
sudo apt install nginx nodejs npm -y
echo -e "✅ \e[32mSuccessfully installed Nginx, NodeJS and npm\e[0m"
nginx -v

# configure firewall
echo -e "\n\e[34mConfiguring firewall ...\e[0m"
echo "Checking firewall status ..."
sudo ufw status
echo "Enabling ssh (22), http (80) and https (443) ports ..."
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw --force enable
echo -e "✅ \e[32mSuccessfully activated the firewall and allowed ssh, http and https ports\e[0m"
sudo ufw status

# setup nginx-facts-website + sites available and enabled
echo -e "\n\e[34mSetting up the website and nginx configs ...\e[0m"
sudo mkdir -p /var/www/nginx-facts-website/html
sudo cp -r demo-website/frontend/build/* /var/www/nginx-facts-website/html/
sudo tee /etc/nginx/sites-available/nginx-facts <<EOF
server {
    # load-balancer server's hostname(nginxloadbalancer.lab), public IP (192.168.100.207) and internal LAN (192.168.10.1)
    server_name nginxloadbalancer.lab 192.168.100.207 192.168.10.1;
    root /var/www/nginx-facts-website/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ /index.html;
    }

    location /api/facts {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }
}
EOF
sudo ln -sf /etc/nginx/sites-available/nginx-facts /etc/nginx/sites-enabled/
sudo nginx -t
# Remove the default Nginx config symlink to prevent conflicts
sudo rm -f /etc/nginx/sites-enabled/default
sudo systemctl reload nginx
echo -e "✅ \e[32mNginx configs for the website successfully setup\e[0m\n"

# setup a separate folder in user's home to store and run the expressjs api from; it's the API's working deirectory
service_name="nginx-facts-api"
service_path="/etc/systemd/system/$service_name.service"
node_bin=$(which node)
echo -e "\e[34mSetting up $service_name ...\e[0m"
mkdir -p $api_folder
cp -r demo-website/backend/* $api_folder
cd $api_folder
# give permissions to api-folder back to user
sudo chown -R "$real_user:$real_user" ~/apis/nginx-facts
npm i

# installing systemd for a persistent running api across reboots
echo -e "\e[34mCreating a $service_name systemd service ...\e[0m"
sudo tee $service_path > /dev/null <<EOF
[Unit]
Description=Persistently running Nginx Facts website API
After=network.target

[Service]
User=$real_user
Group=$real_user
WorkingDirectory=$api_folder
ExecStart=$node_bin $api_folder/server.js
Environment=NODE_ENV=production
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
sudo systemctl daemon-reload
sudo systemctl enable --now "$service_name.service"
# in case of script rerun, this will reload any .env variables updated if any
sudo systemctl restart "$service_name.service"
sudo systemctl status "$service_name.service"
echo -e "\n✅ \e[32m$service_name successfully setup and running persistently through systemd setup\e[0m\n"
