#!/bin/bash

# setup nginx loadbalancer
echo -e "\e[34mSetting up Nginx Loadbalancer ...\e[0m"
sudo tee /etc/nginx/sites-available/nginx-facts-loadbalancer > /dev/null <<EOF
upstream nginx-facts-webapp-servers {
    server webserver1 192.168.10.2;
    server webserver2 192.168.10.3;
}
EOF
sudo ln -sf /etc/nginx/sites-available/nginx-facts-loadbalancer /etc/nginx/sites-enabled/
sudo nginx -t
sudo systemctl reload nginx
echo -e "✅ \e[32mnginx-facts website's loadbalancer successfully setup\e[0m\n"
