#!/bin/bash

# update apt, upgrade system and install nginx
echo -e "\e[34mUpdating apt & system and installing nginx\e[0m"
sudo apt update && sudo apt upgrade -y
sudo apt install nginx -y
echo -e "\e[32mSuccessfully installed Nginx\e[0m"
nginx -v

# configure firewall
echo -e "\n\e[34mConfiguring firewall\e[0m"
echo "Checking firewall status ..."
sudo ufw status
echo "Enabling ssh (22), http (80) and https (443) ports ..."
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw --force enable
echo -e "\e[32mSuccessfully activated the firewall and allowed ssh, http and https ports\e[0m"
sudo ufw status
echo -e "Visit your website served by nginx by typing this in your browser \e[34mhttp://your_server_ip\e[0m"