#!/bin/bash

# enabling port forwarding
sudo vim /etc/sysctl.conf
# Uncomment this line: by removing the #.
net.ipv4.ip_forward=1

# sudo iptables -t nat -A POSTROUTING -o ens33 -j MASQUERADE

# We need to edit /etc/ufw/before.rules. This file is processed before the standard firewall rules.
# You would add the following block at the very top (before the *filter section):
# NAT rules
*nat
:POSTROUTING ACCEPT [0:0]
# Forward traffic from the private LAN (ens34) through the public WAN (ens33)
-A POSTROUTING -s 192.168.10.0/24 -o ens33 -j MASQUERADE
# don't delete the 'COMMIT' line or these rules won't be processed
COMMIT

# in /etc/default/ufw
# change from 'drop' to 'accept' to allow LAN packets from VMs 2/3/4 through to the internet
DEFAULT_FORWARD_POLICY="ACCEPT"
sudo ufw reload

-------------------------------------------------------------------------------------------------------------
script:

# Uncomment net.ipv4.ip_forward=1 in /etc/sysctl.conf
echo -e "\e[34mEnabling IP forwarding in sysctl...\e[0m"
sudo sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf
# Apply the changes immediately without rebooting
sudo sysctl -p
# 1. Change default forward policy to ACCEPT
echo -e "\e[34mUpdating UFW default forward policy...\e[0m"
sudo sed -i 's/DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/' /etc/default/ufw

# 2. Add NAT rules to UFW before.rules if not already present
if ! sudo grep -q "*nat" /etc/ufw/before.rules; then
    echo -e "\e[34mAdding NAT rules to UFW before.rules...\e[0m"
    sudo sed -i '1i # NAT rules\n*nat\n:POSTROUTING ACCEPT [0:0]\n-A POSTROUTING -s 192.168.10.0/24 -o ens33 -j MASQUERADE\nCOMMIT\n' /etc/ufw/before.rules
fi
sudo ufw reload

